In [1]:
import pandas as pd
import numpy as np

df=pd.read_csv('/Users/mingikim/tutorial-env/bin/input/lotto_test.csv')

In [11]:
df.head()

   Unnamed: 0       date  PB1  PB2  PB3  PB4  PB5  Powerball  Unnamed: 8
0         874  2019.8.31    1   15   19   23   28         42          32
1         873  2019.8.24    3    5   12   13   33         39          38
2         872  2019.8.17    2    4   30   32   33         43          29
3         871  2019.8.10    2    6   12   26   30         34          38
4         870   2019.8.3   21   25   30   32   40         42          31

In [13]:
list=["C123", "2020/09"]
list

['C123', '2020/09']

In [16]:
a = list[0]
b = list[1]
if a in list:
    print("yes")
else:
    print("no")

yes

In [4]:
temp=["2019.8"]
temp

['2019.8']

In [10]:
cu = df[df.PB1.str.contains('1')]
cu

AttributeError: Can only use .str accessor with string values!

In [7]:
yes

    Unnamed: 0       date  PB1  PB2  PB3  PB4  PB5  Powerball  Unnamed: 8
0          874  2019.8.31    1   15   19   23   28         42          32
1          873  2019.8.24    3    5   12   13   33         39          38
2          872  2019.8.17    2    4   30   32   33         43          29
3          871  2019.8.10    2    6   12   26   30         34          38
4          870   2019.8.3   21   25   30   32   40         42          31
5          869  2019.7.27    2    6   20   27   37         39           4
6          868  2019.7.20   12   17   28   41   43         44          25
7          867  2019.7.13   14   17   19   22   24         40          41
8          866   2019.7.6    9   15   29   34   37         39          12
9          865  2019.6.29    3   15   22   32   33         45           2
10         864  2019.6.22    3    7   10   13   25         36          32
11         863  2019.6.15   16   21   28   35   39         43          12
12         862   2019.6.8   10   34   38   40   42         43          32
13         861   2019.6.1   11   17   19   21   22         25          24
14         860  2019.5.25    4    8   18   25   27         32          42
15         859  2019.5.18    8   22   35   38   39         41          24
16         858  2019.5.11    9   13   32   38   39         43          23
17         857   2019.5.4    6   10   16   28   34         38          43
18         856  2019.4.27   10   24   40   41   43         44          17
19         855  2019.4.20    8   15   17   19   43         44           7
20         854  2019.4.13   20   25   31   32   36         43           3
21         853   2019.4.6    2    8   23   26   27         44          13
22         852  2019.3.30   11   17   28   30   33         35           9
23         851  2019.3.23   14   18   22   26   31         44          40
24         850  2019.3.16   16   20   24   28   36         39           5
25         849   2019.3.9    5   13   17   29   34         39           3
26         848   2019.3.2    1    2   16   22   38         39          34
27         847  2019.2.23   12   16   26   28   30         42          22
28         846  2019.2.16    5   18   30   41   43         45          13
29         845   2019.2.9    1   16   29   33   40         45           6
30         844   2019.2.2    7    8   13   15   33         45          18
31         843  2019.1.26   19   21   30   33   34         42           4
32         842  2019.1.19   14   26   32   36   39         42          38
33         841  2019.1.12    5   11   14   30   33         38          24
34         840   2019.1.5    2    4   11   28   29         43          27